### PR TITLE
rework extractKeyValuePairs to use custom parser instead of regexp

### PR DESCRIPTION
**Pull request by tirmatovcl**
new benchmarks for current code:

Benchmark_extractKeyValuePairs-4   	  116500	     10015 ns/op	    1301 B/op	      31 allocs/op
BenchmarkParseLogLineFromFiles-4   	     366	   3287822 ns/op	  520184 B/op	    7324 allocs/op
new benchmarks for new parsing code:

Benchmark_extractKeyValuePairs-4   	 1000000	      1093 ns/op	     192 B/op	       6 allocs/op
BenchmarkParseLogLineFromFiles-4   	     770	   1506856 ns/op	  330313 B/op	    3389 allocs/op
So, extractKeyValuePairs is ~10x faster, and overall parser flow is ~2x faster.

### CODE REVIEW

**Comment by adriansr** [comment]
Thanks for your contribution @tirmatovcl , however, we cannot review it unless you sign the CLA. Ping me if you have any issues.

**Comment by adriansr** [comment]
The change seems to be causing some test cases to fail:

```
--- FAIL: TestCoalesceMessages/testdata/ubuntu-16.10-linux-4.8.0.yaml/SERVICE_START (0.00s)
[2021-04-12T10:05:41.993Z] === RUN   TestCoalesceMessages/testdata/ubuntu-16.10-linux-4.8.0.yaml/SERVICE_START
[2021-04-12T10:05:41.993Z]     assertions.go:239: Error Trace:	coalesce_test.go:106
[2021-04-12T10:05:41.993Z]         Error:      	Not equal: 
[2021-04-12T10:05:41.993Z]         expected: map[string]interface {}{"event":map[string]interface {}{"@timestamp":"2017-04-19T18:19:50.183Z", "category":"system-services", "data":map[string]interface {}{"unit":"rsyslog"}, "ecs":map[string]interface {}{"event":map[string]interface {}{"category":[]interface {}{"process"}, "type":[]interface {}{"start"}}, "group":map[string]interface {}{}, "user":map[string]interface {}{"changes":map[string]interface {}{}, "effective":map[string]interface {}{}, "target":map[string]interface {}{}}}, "process":map[string]interface {}{"exe":"/lib/systemd/systemd", "name":"systemd", "pid":"1"}, "record_type":"service_start", "result":"success", "sequence":4083, "session":"unset", "summary":map[string]interface {}{"action":"started-service", "actor":map[string]interface {}{"primary":"unset", "secondary":"0"}, "how":"/lib/systemd/systemd", "object":map[string]interface {}{"primary":"rsyslog", "type":"service"}}, "user":map[string]interface {}{"ids":map[string]interface {}{"auid":"unset", "uid":"0"}}}, "test_name":"SERVICE_START"}
[2021-04-12T10:05:41.993Z]         actual: map[string]interface {}{"event":map[string]interface {}{"@timestamp":"2017-04-19T18:19:50.183Z", "category":"system-services", "ecs":map[string]interface {}{"event":map[string]interface {}{"category":[]interface {}{"process"}, "type":[]interface {}{"start"}}, "group":map[string]interface {}{}, "user":map[string]interface {}{"changes":map[string]interface {}{}, "effective":map[string]interface {}{}, "target":map[string]interface {}{}}}, "process":map[string]interface {}{"pid":"1"}, "record_type":"service_start", "result":"unknown", "sequence":4083, "session":"unset", "summary":map[string]interface {}{"action":"started-service", "actor":map[string]interface {}{"primary":"unset", "secondary":"0"}, "object":map[string]interface {}{"type":"service"}}, "user":map[string]interface {}{"ids":map[string]interface {}{"auid":"unset", "uid":"0"}}}, "test_name":"SERVICE_START", "warnings":[]interface {}{"failed to set object primary using keys=[unit] because they were not found"}}
[2021-04-12T10:05:41.993Z]         
[2021-04-12T10:05:41.993Z]         Diff:
[2021-04-12T10:05:41.993Z]         --- Expected
[2021-04-12T10:05:41.993Z]         +++ Actual
[2021-04-12T10:05:41.994Z]         @@ -1,8 +1,5 @@
[2021-04-12T10:05:41.994Z]         -(map[string]interface {}) (len=2) {
[2021-04-12T10:05:41.994Z]         - (string) (len=5) "event": (map[string]interface {}) (len=11) {
[2021-04-12T10:05:41.994Z]         +(map[string]interface {}) (len=3) {
[2021-04-12T10:05:41.994Z]         + (string) (len=5) "event": (map[string]interface {}) (len=10) {
[2021-04-12T10:05:41.994Z]         (string) (len=10) "@timestamp": (string) (len=24) "2017-04-19T18:19:50.183Z",
[2021-04-12T10:05:41.994Z]         (string) (len=8) "category": (string) (len=15) "system-services",
[2021-04-12T10:05:41.994Z]         -  (string) (len=4) "data": (map[string]interface {}) (len=1) {
[2021-04-12T10:05:41.994Z]         -   (string) (len=4) "unit": (string) (len=7) "rsyslog"
[2021-04-12T10:05:41.994Z]         -  },
[2021-04-12T10:05:41.994Z]         (string) (len=3) "ecs": (map[string]interface {}) (len=3) {
[2021-04-12T10:05:41.994Z]         @@ -27,5 +24,3 @@
[2021-04-12T10:05:41.994Z]         },
[2021-04-12T10:05:41.994Z]         -  (string) (len=7) "process": (map[string]interface {}) (len=3) {
[2021-04-12T10:05:41.994Z]         -   (string) (len=3) "exe": (string) (len=20) "/lib/systemd/systemd",
[2021-04-12T10:05:41.994Z]         -   (string) (len=4) "name": (string) (len=7) "systemd",
[2021-04-12T10:05:41.994Z]         +  (string) (len=7) "process": (map[string]interface {}) (len=1) {
[2021-04-12T10:05:41.994Z]         (string) (len=3) "pid": (string) (len=1) "1"
[2021-04-12T10:05:41.994Z]         @@ -33,6 +28,6 @@
[2021-04-12T10:05:41.994Z]         (string) (len=11) "record_type": (string) (len=13) "service_start",
[2021-04-12T10:05:41.994Z]         -  (string) (len=6) "result": (string) (len=7) "success",
[2021-04-12T10:05:41.994Z]         +  (string) (len=6) "result": (string) (len=7) "unknown",
[2021-04-12T10:05:41.994Z]         (string) (len=8) "sequence": (float64) 4083,
[2021-04-12T10:05:41.994Z]         (string) (len=7) "session": (string) (len=5) "unset",
[2021-04-12T10:05:41.994Z]         -  (string) (len=7) "summary": (map[string]interface {}) (len=4) {
[2021-04-12T10:05:41.994Z]         +  (string) (len=7) "summary": (map[string]interface {}) (len=3) {
[2021-04-12T10:05:41.994Z]         (string) (len=6) "action": (string) (len=15) "started-service",
[2021-04-12T10:05:41.994Z]         @@ -42,5 +37,3 @@
[2021-04-12T10:05:41.994Z]         },
[2021-04-12T10:05:41.994Z]         -   (string) (len=3) "how": (string) (len=20) "/lib/systemd/systemd",
[2021-04-12T10:05:41.994Z]         -   (string) (len=6) "object": (map[string]interface {}) (len=2) {
[2021-04-12T10:05:41.994Z]         -    (string) (len=7) "primary": (string) (len=7) "rsyslog",
[2021-04-12T10:05:41.994Z]         +   (string) (len=6) "object": (map[string]interface {}) (len=1) {
[2021-04-12T10:05:41.994Z]         (string) (len=4) "type": (string) (len=7) "service"
[2021-04-12T10:05:41.994Z]         @@ -55,3 +48,6 @@
[2021-04-12T10:05:41.994Z]         },
[2021-04-12T10:05:41.994Z]         - (string) (len=9) "test_name": (string) (len=13) "SERVICE_START"
[2021-04-12T10:05:41.994Z]         + (string) (len=9) "test_name": (string) (len=13) "SERVICE_START",
[2021-04-12T10:05:41.994Z]         + (string) (len=8) "warnings": ([]interface {}) (len=1) {
[2021-04-12T10:05:41.994Z]         +  (string) (len=74) "failed to set object primary using keys=[unit] because they were not found"
[2021-04-12T10:05:41.994Z]         + }
[2021-04-12T10:05:41.994Z]         }
[2021-04-12T10:05:41.994Z]         Messages:   	file=testdata/ubuntu-16.10-linux-4.8.0.yaml test_case=SERVICE_START
```

**Comment by andrewkroh** [comment]
Looks like this has stalled out due to failing tests.

**Pull request closed without merging**
