### PR TITLE
Adding Big Endian Support

### PR DESCRIPTION
**Pull request by vitt-bagal**
Adding big endian support for go-libaudit library to resolve issue related to audit service start

### CODE REVIEW

**Comment by andrewkroh** [comment]
Thanks for the contribution. Can you please sign the [Elastic contributor license agreement (CLA)](https://www.elastic.co/contributor-agreement)?

The build is failing because of:

```
$ go test -v $(go list ./... | grep -v /vendor/)
# github.com/elastic/go-libaudit
import cycle not allowed in test
package github.com/elastic/go-libaudit (test)
	imports github.com/elastic/go-libaudit/rule
	imports github.com/elastic/go-libaudit
```

**Comment by vitt-bagal** [comment]
@andrewkroh Thanks for the direction. I am still working on final changes for this PR and facing integration test case failures on s390x While executing command `go test -v rule_integ_test.go`, below is the error log:

--- FAIL: TestBuildGolden/22-ignore-chrony.rules.golden.yml (0.00s)
    --- FAIL: TestBuildGolden/22-ignore-chrony.rules.golden.yml/rule_0 (0.00s)
                rule_integ_test.go:78: rule: -a never,exit -F arch=b64 -S adjtimex -F auid=unset -F uid=20 -F subj_type=chronyd_t
                rule_integ_test.go:93: rule: -a never,exit -F arch=b64 -S adjtimex -F auid=unset -F uid=20 -F subj_type=chronyd_t error: failed to add filter '{2 arch = b64}': cannot use b64 on s390x

As suggested in [CHANGELOG.md](https://github.com/elastic/go-libaudit/blob/39073a2988f718067d85d27a4d18b1b57de5d947/CHANGELOG.md#011), added `-F arch=s390x` in rules. However still tests are failing with assertion failure for byte values.

**Comment by andrewkroh** [comment]
The golden data was generated on a little endian machine so if you test on a different endian machine the golden data isn't going to match up. You'll probably have to skip those tests by adding a `if endian != little { t.Skip("golden test data is for little endian, but test machine is big endian") }`.

**Comment by vitt-bagal** [comment]
@andrewkroh Thanks for the suggestion on integration test case failures on s390x. Do i need to skip *TestAddRule* and *TestAddDuplicateRule* tests from libaudit module? as these tests are failing for root user with below error log :

**Comment by andrewkroh** [comment]
Both of those test rely on [binary data](https://github.com/elastic/go-libaudit/blob/0c842c62c7c04344b204e2059eadd98c757defe0/audit_test.go#L49-L51) that was generated on LE machine so skipping them when not on LE makes sense to me.

**Comment by vitt-bagal** [comment]
@andrewkroh Thanks for your help. Added few code changes to fix CI issue, test failures on s390x and signed **CLA**.

**Comment by vitt-bagal** [comment]
@andrewkroh I have signed **CLA**. Do I need to create new pull request with above code changes?

**Comment by andrewkroh** [comment]
I manually checked the CLA database and didn't find your GH handle or your email (from the commit data). Not sure what went wrong. Can you try signing it again. In the meantime I'll review the latest changes.

**Comment by vitt-bagal** [comment]
@andrewkroh Just to confirm. I have signed CLA, got mail with subject line as `CCLA between Elasticsearch Inc and vitthal is Signed and Filed!` and  **CCLA-signed.pdf** in attachment.
Still do I need to sign it again ?

**Comment by andrewkroh** [comment]
Hi @karmi, I used the web portal to try and search via Github username and also email, but neither found any signatures. Can you help me here an take a look at this? Thanks

**Comment by karmi** [comment]
Hello @vitt-bagal, sorry for the trouble with CLA! I have also searched for a different combinations of your name and email in our records, but can't find any record...

Since you mention a CCLA — are you adding your signature for an existing "Corporate CLA Agreement" in your company? In that case, you have to choose the option _An individual contributing under an existing company contributor agreement_ at https://www.elastic.co/contributor-agreement/...

**Comment by vitt-bagal** [comment]
@karmi Thanks for your help. 
I have signed agreement with an option :  `A company wanting its employees to contribute`   with github id: vitt-bagal and email : vitthalb@us.ibm.com

Received CCLA email as From: Carl Spataro (Elasticsearch Inc) To:    Carl Spataro and vitthal
Should I try creating new pull request or signing agreement with other option ?

**Comment by karmi** [comment]
@vitt-bagal, that's probably what's throwing our automation off. The option you have choosed is for _companies_ which provide an umbrella agreement to their employees, not individuals.

If you want to sign this agreement — assuming you're authorized to do so on behalf of your company  — that's fine, but each individual under that "umbrella" agreement has to sign the agreement individually as well, under the option _An individual contributing under an existing company contributor agreement_.

**Comment by vitt-bagal** [comment]
@karmi Earlier we had raised [PR ](https://github.com/elastic/gosigar/pull/100) and followed same steps to sign CLA & CLA checker was able to find record successfully. 
Could you please recheck once if my github id or email is available in *CLA database* ?

**Comment by karmi** [comment]
@vitt-bagal , right, I can see that [the email](https://patch-diff.githubusercontent.com/raw/elastic/gosigar/pull/100.patch) from the other PR is indeed in our records. But I can't find any record for the [email](https://patch-diff.githubusercontent.com/raw/elastic/go-libaudit/pull/48.patch) in this patch...

If your company has the CCLA already, you still need to sign the CLA under the _An individual contributing under an existing company contributor agreement_ option, I'm afraid. I know it might not be intuititive, but this is the workflow where your email appears in the records, and is automatically green-lighted by the service... Can you try that option?

**Comment by vitt-bagal** [comment]
@karmi I have received CCLA email from **Carl Spataro** whereas in [PR ](https://github.com/elastic/gosigar/pull/100) we got CCLA email from **CLA Committers**
Are there any changes being made in CLA process ?

**Comment by vitt-bagal** [comment]
>If your company has the CCLA already, you still need to sign the CLA under the _An individual contributing under an existing company contributor agreement_ option, I'm afraid. I know it might not be intuititive, but this is the workflow where your email appears in the records, and is automatically green-lighted by the service... Can you try that option?

@karmi I have signed CLA with option **`An individual contributing under an existing company contributor agreement.`**
Can you please check **CLA database** to confirm my github id or email are reflected in database ?

**Comment by andrewkroh** [comment]
@vitt-bagal  Sorry for the delay. We're working on fix to the CLA tool. Something in the pipeline that updates the database of signers isn't working.

**Comment by andrewkroh** [comment]
The CLA tool should be fixed now, can you please sign it now under the same "An individual contributing under an existing company contributor agreement" option. Sorry for the problems.

**Comment by vitt-bagal** [comment]
>The CLA tool should be fixed now, can you please sign it now under the same "An individual contributing under an existing company contributor agreement" option. Sorry for the problems.

@andrewkroh I have signed CLA again with the same option **`An individual contributing under an existing company contributor agreement`** & CLA check is not passed yet.
Can you please check **CLA database** to confirm my github id or email are reflected in database ?

**Comment by andrewkroh** [comment]
Thanks

**Pull request merged**
